name: Build and release workflow

on:
  push:
    tags:
     - 'v*'
  workflow_dispatch:

jobs:
  release:
    name: Build and release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-versions: [ "3.8", "3.9", "3.10", "3.11" ]

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-versions }}

    - name: Install poetry
      run: >-
        python -m pip install --upgrade pip
        python -m pip install poetry twine

    - name: Build package
      run: >-
        poetry build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
